### ISSUE TITLE
Streaming data

### ISSUE THREAD

**Issue by tommyengstrom** [tommyengstrom/domain-driven#14]
Current persistance API relies on lists. This is not going to be a reasonable choice when the amount of data gets larger. We need to move to a streaming model.

## Tasks

- [x] Use `streamly` for streaming
- [x] Refactor `getEvents` get return a stream
- [x] Upate the persistance modules
