### ISSUE TITLE
Generate server

### ISSUE THREAD

**Issue by tommyengstrom** [tommyengstrom/domain-driven#5]
Given a `Model` and corresponding commands and/or views, it should be possible to generate the server. Generics is not available to us due to the usage of GADTs for commands and queries. 

## Tasks
- [x] Generate server given a model and a command handler
- [x] Generate server given model and queries
- [x] Support hierarchical models
